apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- complete-demo.yaml
namespace: sock-shop
images:
- name: weaveworksdemos/carts
  newName: ttl.sh/carts-cfe678b8e4f7e6ba7db5a440f9e369f56b959ef2
  newTag: 2h
- name: weaveworksdemos/queue-master
  newName: ttl.sh/queue-master-53d46feea3c4bdf2cfe0e9de7188b07dfe7684ca
  newTag: 2h
- name: xweaveworksdemos/catalogue
  newName: x
  newTag: 2h
- name: xweaveworksdemos/catalogue-db
  newName: x
  newTag: latest
- name: xweaveworksdemos/front-end
  newName: x
  newTag: latest
- name: xweaveworksdemos/orders
  newName: x
  newTag: latest
- name: xweaveworksdemos/payment
  newName: x
  newTag: latest
- name: xweaveworksdemos/shipping
  newName: x
  newTag: latest
- name: xweaveworksdemos/user
  newName: x
  newTag: latest
