apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- complete-demo.yaml
namespace: sock-shop
images:
- name: weaveworksdemos/carts
  newName: weaveworksdemos/carts
  newTag: 0.4.8
- name: weaveworksdemos/front-end
  newName: ttl.sh/front-end-7f79d79d681476dd433565ea777d0853d7b2ed77
  newTag: 2h
- name: weaveworksdemos/orders
  newName: ttl.sh/orders-2eeb1af0e9316fa10004f48dc91acd61cd57123a
  newTag: 2h
- name: weaveworksdemos/queue-master
  newName: ttl.sh/queue-master-53d46feea3c4bdf2cfe0e9de7188b07dfe7684ca
  newTag: 2h
- name: weaveworksdemos/shipping
  newName: ttl.sh/shipping-7895eb928ce1586f24c7a068db876a0299f2fcad
  newTag: 2h
- name: xweaveworksdemos/catalogue
  newName: x
  newTag: 2h
- name: xweaveworksdemos/catalogue-db
  newName: x
  newTag: latest
- name: xweaveworksdemos/front-end
  newName: x
  newTag: latest
- name: xweaveworksdemos/orders
  newName: x
  newTag: latest
- name: xweaveworksdemos/payment
  newName: x
  newTag: latest
- name: xweaveworksdemos/shipping
  newName: x
  newTag: latest
- name: xweaveworksdemos/user
  newName: x
  newTag: latest
