apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- complete-demo.yaml
namespace: sock-shop
images:
- name: blabla
  newName: ttl.sh/otus-endgame-queue-master
  newTag: latest
- name: weaveworksdemos/queue-master
  newName: ttl.sh/queue-master-53d46feea3c4bdf2cfe0e9de7188b07dfe7684ca
  newTag: 2h
