# This is a basic workflow to help you get started with Actions

name: CI-argo-apps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - sockshop/initial/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  argocd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # install terraform
    steps:

     - name: Check out code
       uses: actions/checkout@v3
       with:
         repository: suxarikisme/endgame
         ref: refs/heads/master

     - name: Install argocd cli
       run: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

     - name: Argo CD login
       run: |
        argocd login argo.51.250.86.77.nip.io --insecure --username admin --password "${{ secrets.ARGO_PASS }}"

     - name: Argo create apps
       run: |
        argocd app list | grep -q "^sock-shop " || argocd app create sock-shop --repo https://github.com/suxarikisme/endgame --path workpath/app --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse

        argocd app list | grep -q "^ingress-sock-shop " || argocd app create ingress-sock-shop --repo https://github.com/suxarikisme/endgame --path workpath/app/ingress --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse

        argocd app list | grep -q "^jaeger " || argocd app create jaeger --repo https://github.com/suxarikisme/endgame --path workpath/jaeger --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse

        argocd app list | grep -q "^loki " || argocd app create loki --repo https://github.com/suxarikisme/endgame --path workpath/loki --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse --helm-set replicaCount=1

        argocd app list | grep -q "^ingress-grafana " || argocd app create ingress-grafana --repo https://github.com/suxarikisme/endgame --path workpath/grafana --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse

        argocd app list | grep -q "^vm-cluster " || argocd app create vm-cluster --repo https://github.com/suxarikisme/endgame --path workpath/vm/victoria-metrics-cluster --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse --helm-set replicaCount=1    

        argocd app list | grep -q "^vm-agent " || argocd app create vm-cluster --repo https://github.com/suxarikisme/endgame --path workpath/vm/victoria-metrics-agent --dest-namespace default --dest-server https://kubernetes.default.svc --directory-recurse --helm-set replicaCount=1       