# This is a basic workflow to help you get started with Actions

name: CI-payment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - sockshop/payment/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GROUP: sockshop
      COMMIT: ${{ github.sha }}
      REPO: payment
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/endgame/endgame/go

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: microservices-demo/payment
          ref: refs/heads/master

      - name: GO Installation
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }} # The GO version to make available on the path.

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          go get -u github.com/mattn/goveralls
          go get -u github.com/FiloSottile/gvt
          gvt restore
                    
          sed '/^FROM golang.*/a RUN apk add ca-certificates && update-ca-certificates' /home/runner/work/endgame/endgame/docker/payment/Dockerfile > /home/runner/work/endgame/endgame/docker/payment/Dockerfile.changed
          cat /home/runner/work/endgame/endgame/docker/payment/Dockerfile

       # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Build go
        run: |
          export BUILD_VERSION="0.0.2-SNAPSHOT"
          export BUILD_DATE=`date +%Y-%m-%dT%T%z`
          echo $(pwd)
          CODE_DIR=/home/runner/work/endgame/endgame
          
          cp -r $CODE_DIR/cmd/ $CODE_DIR/docker/payment/cmd/
          cp $CODE_DIR/*.go $CODE_DIR/docker/payment/
          mkdir $CODE_DIR/docker/payment/vendor && cp $CODE_DIR/vendor/manifest $CODE_DIR/docker/payment/vendor/
          
          docker build -t ttl.sh/payment-dev -f $CODE_DIR/docker/payment/Dockerfile.changed $CODE_DIR/docker/payment;
          docker create --name payment ttl.sh/payment-dev
          docker cp payment:/app $CODE_DIR/docker/payment/app
          docker rm payment
          build -t ttl.sh/payment-${{ github.sha }}:2h -f $CODE_DIR/docker/payment/Dockerfile-release $CODE_DIR/docker/payment

          docker push ttl.sh/payment-${{ github.sha }}:2h                         

  deploy:
    name: Update
    runs-on: ubuntu-latest
    needs: build     

    steps:   
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: suxarikisme/endgame
          ref: refs/heads/master

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
          
      - name: Update Kubernetes res-payment
        run: |
         cd workpath/app/
         kustomize edit set image weaveworksdemos/payment=ttl.sh/payment-$GITHUB_SHA:2h
         cat kustomization.yaml
         
      - name: Commit files
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git commit -am "Bump docker image and tag for payment"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.PUSH }}
