# This is a basic workflow to help you get started with Actions

name: CI-orders

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - sockshop/orders/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GROUP: sockshopdemo 
      COMMIT: ${{ github.sha }}
      REPO: orders

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: microservices-demo/orders
          ref: refs/heads/master

      - name: Java Installation
        uses: actions/setup-java@v1
        with:
          java-version: '1.8' # The JDK version to make available on the path.

       # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml
                
      - name: Build image and push to ttl.sh
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./docker/orders/
          # Note: tags has to be all lower-case
          tags: ttl.sh/orders-${{ github.sha }}:2h 
          push: true

  deploy:
    name: Update
    runs-on: ubuntu-latest
    needs: build     

    steps:   
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: suxarikisme/endgame
          ref: refs/heads/master

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
          
      - name: Update Kubernetes resources
        run: |
         cd workpath/app/
         kustomize edit set image weaveworksdemos/orders=ttl.sh/orders-$GITHUB_SHA:2h
         cat kustomization.yaml
         
      - name: Commit files
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git commit -am "Bump docker image and tag for orders"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.PUSH }}
