# This is a basic workflow to help you get started with Actions

name: CI-initial

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - sockshop/initial/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  yandex-cloud:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # install terraform
    steps:

     - name: Check out code
       uses: actions/checkout@v3
       with:
         repository: suxarikisme/endgame
         ref: refs/heads/master

     - name: Install Terraform
       uses: hashicorp/setup-terraform@v2

     - name: Install YC
       run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash 

     - name: Run Terraform init
       run: |
        cd /home/runner/work/endgame/endgame/initial && terraform init

     - name: Run Terraform apply
       run: |
        cd /home/runner/work/endgame/endgame/initial && terraform apply
       